SASSC_VERSION = 3.6.2
SASSC_SITE = $(call github,sass,sassc,$(SASSC_VERSION))
SASSC_LICENSE = MIT
SASSC_LICENSE_FILES = LICENSE
SASSC_AUTORECONF = YES
HOST_SASSC_AUTORECONF_ENV = SASSC_VERSION=$(SASSC_VERSION)
HOST_SASSC_DEPENDENCIES = host-libsass
HOST_SASSC_CONF_OPTS = --with-libsass=$(HOST_DIR)

$(eval $(host-autotools-package))
