apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: llm-d
  namespace: kube-system
spec:
  chart: oci://ghcr.io/llm-d/charts/llm-d-router-gateway@sha256:63a79a842974691be73d44918c7086bcc52d6fee546ff39113517a23c03eeab0
  version: v0.11.0
  targetNamespace: puu-ai
  createNamespace: true
  valuesContent: |-
    provider:
      name: none

    router:
      epp:
        image:
          tag: v0.11.0@sha256:39257d24552d16d8f215d3de25cc734fd44af3b282b67032db01aff900c610cf
          pullPolicy: IfNotPresent
        flags:
          v: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi

      modelServers:
        targetPorts:
          - number: 8000
        type: vllm
        protocol: http
        matchLabels:
          puu.ai/inference: "enabled"
          puu.ai/model-server: vllm
          puu.ai/model-capacity: gpu
          puu.ai/model-source: local-discovery
          puu.ai/cluster-routing: "enabled"

    httpRoute:
      create: true
      inferenceGatewayName: llm-d-inference-gateway
      requestTimeout: 300s
