apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: llm-d
  namespace: kube-system
spec:
  chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool@sha256:bc6b00e127fe93961c4788e99abc398efff7344cc427e3620deb2027191db197
  version: v1.5.0
  targetNamespace: puu-ai
  createNamespace: true
  valuesContent: |-
    provider:
      name: none

    inferenceExtension:
      image:
        tag: v1.5.0@sha256:86c679b057298e68c6e65ff5603e92066d432e77b11f1f81f0a06399694810bc
        pullPolicy: IfNotPresent
      flags:
        v: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi

    inferencePool:
      targetPorts:
        - number: 8000
      modelServerType: vllm
      modelServerProtocol: http
      modelServers:
        matchLabels:
          puu.ai/inference: "enabled"
          puu.ai/model-server: vllm
          puu.ai/model-capacity: gpu
          puu.ai/model-source: local-discovery
          puu.ai/cluster-routing: "enabled"

    experimentalHttpRoute:
      enabled: true
      inferenceGatewayName: llm-d-inference-gateway
      requestTimeout: 300s
