apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: litellm
  namespace: kube-system
spec:
  chart: oci://docker.litellm.ai/berriai/litellm-helm@sha256:e528ce9c544c55368ff2a1736136cc9154b85fb1d8084040848a4da3e813dcd4
  version: 1.90.1
  targetNamespace: puu-ai
  createNamespace: true
  valuesContent: |-
    fullnameOverride: litellm

    image:
      repository: ghcr.io/berriai/litellm
      tag: 1.90.1@sha256:09d98fd0c82d1a3731577fde7fe2f65db0afa4453e9da45c11ecda94d047248f
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 4000

    db:
      deployStandalone: false
      useExisting: true
      database: litellm
      secret:
        name: puu-litellm-db
        endpointKey: endpoint

    migrationJob:
      enabled: true

    proxy_config:
      model_list:
        - model_name: "bonsai-2-27b"
          litellm_params:
            model: openai/Bonsai-2-27B
            api_base: http://bonsai-2-27b.puu-ai.svc.cluster.local:8000/v1
            api_key: none
        - model_name: "*"
          litellm_params:
            model: openai/*
            api_base: http://llm-d-inference-gateway.puu-ai.svc.cluster.local:8000/v1
            api_key: none
      general_settings:
        disable_auth: true
        max_parallel_requests: 32
      router_settings:
        timeout: 1200
        num_retries: 0
