d /var/lib/rancher/k3s/server                  0700 root root -
d /var/lib/rancher/k3s/server/manifests        0700 root root -
d /var/lib/puu                                 0700 root root -
d /var/lib/puu/vllm                             0755 root root -
d /var/lib/puu/open-webui                       0755 root root -
d /var/lib/puu/postgresql                      0700 root root -
d /etc/credstore.encrypted                      0700 root root -
