LIBSASS_VERSION = 3.6.6
LIBSASS_SITE = $(call github,sass,libsass,$(LIBSASS_VERSION))
LIBSASS_LICENSE = MIT
LIBSASS_LICENSE_FILES = LICENSE

HOST_LIBSASS_MAKE_OPTS = \
	BUILD=static \
	LIBSASS_VERSION=$(LIBSASS_VERSION) \
	PREFIX=$(HOST_DIR)

define HOST_LIBSASS_BUILD_CMDS
	$(HOST_MAKE_ENV) $(HOST_CONFIGURE_OPTS) $(MAKE) -C $(@D) \
		$(HOST_LIBSASS_MAKE_OPTS)
endef

define HOST_LIBSASS_INSTALL_CMDS
	$(HOST_MAKE_ENV) $(HOST_CONFIGURE_OPTS) $(MAKE) -C $(@D) \
		$(HOST_LIBSASS_MAKE_OPTS) install-static install-headers
endef

$(eval $(host-generic-package))
