if [[ "${DRACUT_ARCH}" == x86_64 ]]; then
    install_items+=" /usr/lib/firmware/rtl_bt/rtl8852bu_fw.bin /usr/lib/firmware/rtl_bt/rtl8761bu_config.bin /usr/lib/firmware/rtl_bt/rtl8852bu_config.bin "
fi
