ADWAITA_FONTS_VERSION_MAJOR = 51
ADWAITA_FONTS_VERSION = $(ADWAITA_FONTS_VERSION_MAJOR).0
ADWAITA_FONTS_SOURCE = adwaita-fonts-$(ADWAITA_FONTS_VERSION).tar.xz
ADWAITA_FONTS_SITE = https://download.gnome.org/sources/adwaita-fonts/$(ADWAITA_FONTS_VERSION_MAJOR)
ADWAITA_FONTS_LICENSE = GPL-3.0+
ADWAITA_FONTS_LICENSE_FILES = LICENSE

$(eval $(meson-package))
