EVOLUTION_DATA_SERVER_VERSION_MAJOR = 3.60
EVOLUTION_DATA_SERVER_VERSION = $(EVOLUTION_DATA_SERVER_VERSION_MAJOR).2
EVOLUTION_DATA_SERVER_SOURCE = evolution-data-server-$(EVOLUTION_DATA_SERVER_VERSION).tar.xz
EVOLUTION_DATA_SERVER_SITE = https://download.gnome.org/sources/evolution-data-server/$(EVOLUTION_DATA_SERVER_VERSION_MAJOR)
EVOLUTION_DATA_SERVER_LICENSE = LGPL-2.1+
EVOLUTION_DATA_SERVER_LICENSE_FILES = COPYING
EVOLUTION_DATA_SERVER_INSTALL_STAGING = YES
# Keep msgmerge output separate from the source translations read by msgfmt.
EVOLUTION_DATA_SERVER_SUPPORTS_IN_SOURCE_BUILD = NO
EVOLUTION_DATA_SERVER_DEPENDENCIES = \
	host-pkgconf \
	icu \
	json-glib \
	libglib2 \
	libical \
	libnspr \
	libnss \
	libsecret \
	libsoup3 \
	libxml2 \
	libxslt \
	sqlite

# C17 compatibility with default C23 toolchains.
EVOLUTION_DATA_SERVER_CONF_OPTS = \
	-DCMAKE_C_STANDARD=17 \
	-DSYSCONF_INSTALL_DIR=/etc \
	-D_correct_iconv_EXITCODE=0 \
	-DHAVE_LKSTRFTIME_EXITCODE=0 \
	-D_decoded_EXITCODE=0 \
	-DENABLE_TESTS=OFF \
	-DENABLE_INSTALLED_TESTS=OFF \
	-DENABLE_EXAMPLES=OFF \
	-DENABLE_GTK=OFF \
	-DENABLE_GTK4=OFF \
	-DENABLE_GOA=OFF \
	-DENABLE_WEATHER=OFF \
	-DENABLE_CANBERRA=OFF \
	-DENABLE_INTROSPECTION=OFF \
	-DENABLE_VALA_BINDINGS=OFF \
	-DENABLE_GTK_DOC=OFF \
	-DENABLE_FILE_LOCKING=fcntl \
	-DWITH_PHONENUMBER=OFF \
	-DWITH_LIBDB=OFF \
	-DWITH_KRB5=OFF \
	-DWITH_OPENLDAP=OFF \
	-DENABLE_OAUTH2_WEBKITGTK=OFF \
	-DENABLE_OAUTH2_WEBKITGTK4=OFF

ifeq ($(BR2_PACKAGE_SYSTEMD),y)
EVOLUTION_DATA_SERVER_DEPENDENCIES += systemd
EVOLUTION_DATA_SERVER_CONF_OPTS += -DWITH_SYSTEMD_USER_UNITS=ON
else
EVOLUTION_DATA_SERVER_CONF_OPTS += -DWITH_SYSTEMD_USER_UNITS=OFF
endif

define EVOLUTION_DATA_SERVER_INSTALL_GENERATED_TABLES
	$(INSTALL) -m 0644 $(EVOLUTION_DATA_SERVER_PKGDIR)/camel-mime-tables.c \
		$(@D)/src/camel/camel-mime-tables.c
	$(INSTALL) -m 0644 $(EVOLUTION_DATA_SERVER_PKGDIR)/e-name-western-tables.h \
		$(@D)/src/addressbook/libebook-contacts/e-name-western-tables.h
endef
EVOLUTION_DATA_SERVER_POST_PATCH_HOOKS += EVOLUTION_DATA_SERVER_INSTALL_GENERATED_TABLES

# Pre-generated iconv aliases for cross-compilation.
define EVOLUTION_DATA_SERVER_INSTALL_ICONV_DETECT_H
	$(INSTALL) -m 0644 $(EVOLUTION_DATA_SERVER_PKGDIR)/iconv-detect.h \
		$(EVOLUTION_DATA_SERVER_BUILDDIR)/iconv-detect.h
endef
EVOLUTION_DATA_SERVER_POST_CONFIGURE_HOOKS += EVOLUTION_DATA_SERVER_INSTALL_ICONV_DETECT_H

# Locate host libxml2 for gen-western-table.
EVOLUTION_DATA_SERVER_MAKE_ENV = \
	LD_LIBRARY_PATH=$(HOST_DIR)/lib:$$LD_LIBRARY_PATH

define EVOLUTION_DATA_SERVER_REMOVE_MISSING_ALARM_NOTIFY_AUTOSTART
	rm -f \
		$(TARGET_DIR)/etc/xdg/autostart/org.gnome.Evolution-alarm-notify.desktop \
		$(TARGET_DIR)/usr/share/applications/org.gnome.Evolution-alarm-notify.desktop
endef
EVOLUTION_DATA_SERVER_POST_INSTALL_TARGET_HOOKS += \
	EVOLUTION_DATA_SERVER_REMOVE_MISSING_ALARM_NOTIFY_AUTOSTART

$(eval $(cmake-package))
