BLUEPRINT_COMPILER_VERSION_MAJOR = 0.22
BLUEPRINT_COMPILER_VERSION = $(BLUEPRINT_COMPILER_VERSION_MAJOR).2
BLUEPRINT_COMPILER_SOURCE = blueprint-compiler-$(BLUEPRINT_COMPILER_VERSION).tar.xz
BLUEPRINT_COMPILER_SITE = https://download.gnome.org/sources/blueprint-compiler/$(BLUEPRINT_COMPILER_VERSION_MAJOR)
BLUEPRINT_COMPILER_LICENSE = LGPL-3.0+
BLUEPRINT_COMPILER_LICENSE_FILES = COPYING
HOST_BLUEPRINT_COMPILER_DEPENDENCIES = \
	host-python-gobject
$(eval $(host-meson-package))
