d /var/lib/rancher     0700 root root -
d /var/lib/rancher/etc 0700 root root -
d /var/lib/rancher/k3s 0700 root root -
d /var/lib/kubelet     0700 root root -
d /var/lib/kubelet/volume-plugins 0755 root root -
