GWEATHER_LOCATIONS_VERSION_MAJOR = 2026
GWEATHER_LOCATIONS_VERSION = $(GWEATHER_LOCATIONS_VERSION_MAJOR).2
GWEATHER_LOCATIONS_SOURCE = gweather-locations-$(GWEATHER_LOCATIONS_VERSION).tar.xz
GWEATHER_LOCATIONS_SITE = https://download.gnome.org/sources/gweather-locations/$(GWEATHER_LOCATIONS_VERSION_MAJOR)
GWEATHER_LOCATIONS_LICENSE = CC-BY-SA-3.0
GWEATHER_LOCATIONS_LICENSE_FILES = COPYING
GWEATHER_LOCATIONS_INSTALL_STAGING = YES
GWEATHER_LOCATIONS_DEPENDENCIES = \
	host-pkgconf \
	host-python-gobject

$(eval $(meson-package))
