LIBGRAPHEME_VERSION = 3.0.0
LIBGRAPHEME_SITE = https://dl.suckless.org/libgrapheme
LIBGRAPHEME_LICENSE = ISC
LIBGRAPHEME_LICENSE_FILES = LICENSE
LIBGRAPHEME_INSTALL_STAGING = YES

define LIBGRAPHEME_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS) -fPIC" \
		LDFLAGS="$(TARGET_LDFLAGS)" \
		BUILD_CC="$(HOSTCC)" \
		BUILD_CPPFLAGS="$(HOST_CPPFLAGS)" \
		BUILD_CFLAGS="$(HOST_CFLAGS)" \
		BUILD_LDFLAGS="$(HOST_LDFLAGS)"
endef

define LIBGRAPHEME_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) \
		DESTDIR=$(STAGING_DIR) PREFIX=/usr LDCONFIG=true install
endef

define LIBGRAPHEME_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) \
		DESTDIR=$(TARGET_DIR) PREFIX=/usr LDCONFIG=true install
endef

$(eval $(generic-package))
